CONFIG_SINGLE_APPLICATION_SLOT=y
CONFIG_MCUBOOT_BOOTLOADER_MODE_OVERWRITE_ONLY=y

# USB needs kernel primitives
CONFIG_MULTITHREADING=y
CONFIG_SYSTEM_WORKQUEUE=y
CONFIG_WORK_QUEUE=y
CONFIG_POLL=y

CONFIG_SEMAPHORE=y
CONFIG_MUTEX=y
CONFIG_QUEUE=y

CONFIG_THREAD_NAME=y
